Edit busdb script -  Change from: if [[ -n ${ExtComm[@]} ]]; then, to: if (( ${#ExtComm[@]} )); then, when checking for External Commands. -  Add an -e test when checking for directory/destination and the database if it exists.

diff --git a/busdb b/busdb
--- a/busdb
+++ b/busdb
@@ -4,9 +4,9 @@
 #: Title           : busdb                                                                     #
 #: Sypnosis        : busdb [OPTIONS]... [ARGS]                                                 #
 #: Date Created    : Tue 30 Jan 2018 07:26:31 AM +08  /  Mon Jan 29 23:26:31 UTC 2018          #
-#: Last Edit       : Wed 19 Sep 2018 10:16:07 AM +08  /  Wed Sep 19 02:16:07 UTC 2018          #
+#: Last Edit       : Wed 19 Sep 2018 22:39:32 PM +08  /  Wed Sep 19 14:39:32 UTC 2018          #
 #: License         : GPL3+                                                                     #
-#: Version         : 1.0.1                                                                     #
+#: Version         : 1.0.2                                                                     #
 #: Author          : Jason V. Ferrer '<jetchisel@opensuse.org>'                                #
 #: Description     : A backup script for sqlite3 database.                                     #
 #: Options         : [hfd]                                                                     #
@@ -81,7 +81,7 @@ Missing=()
 MissingMessage="is either not installed or it is not in your PATH!"
 ExitMessage="Please install the following: "
 
-if [[ -n ${ExtComm[@]} ]]; then
+if (( ${#ExtComm[@]} )); then
   for apps in "${ExtComm[@]}"; do
     if ! type -P "$apps" >/dev/null; then
       printf '%s %s\n' "$apps" "$MissingMessage" >&2
@@ -194,6 +194,7 @@ while [[ $1 = -?* ]]; do
         (( EUID > 0 )) && database=${HOME%"$LOGNAME"}${database#*?}
         (( EUID == 0 )) && database=/${database#*?}
       fi
+      [[ -e $database ]] || die "[$database] does not exists!" "please fix the error, then try again." 1
       output=$(file -- "$database")
       [[ "$output" = *'SQLite 3.x database'* ]] || die "Something seems to be wrong with [$database]" "file_type: [$output]" 1
       file=1
@@ -207,9 +208,10 @@ while [[ $1 = -?* ]]; do
         (( EUID > 0 )) && destination=${HOME%"$LOGNAME"}${destination#*?}
         (( EUID == 0 )) && destination=/${destination#*?}
       fi
-      [[ -d $destination ]] || die "$destination is not a directory!" "please fix the error, then try again." 1
-      [[ -x $destination ]] || die "Check your permissions in \`$destination'." "please fix the error, then try again." 1
-      [[ -w $destination ]] || die "Check your permissions in \`$destination'." "please fix the error, then try again." 1
+      [[ -e $destination ]] || die "[$destination] does not exists!" "please fix the error, then try again." 1
+      [[ -d $destination ]] || die "[$destination] is not a directory!" "please fix the error, then try again." 1
+      [[ -x $destination ]] || die "Check your permissions in [$destination]." "please fix the error, then try again." 1
+      [[ -w $destination ]] || die "Check your permissions in [$destination]." "please fix the error, then try again." 1
       [[ $destination = */ ]] && destination=${destination%/*}
       directory=1
       ;;
