Edit Readme. -  Add info on howto use bus-db.
Edit the busdb script.
-  Change the Description entry from: `A script to backup the sdb database.' to: `A backup script for sqlite3 database.'
-  Add the following entry at the help menu.
   * Back up sqlite3 database.
   * A backup shell script for sqlite3 database.
-  Remove the AUTOMATED BACKUP entry at the help menu.
   * Instructions is in the README file instead.
-  Remove the BCD entry at the optstring. (It may be added later.)
-  Fix bug when using the = in the options. Since tilde does not expand in quotes and parsing that option requires it to be quoted.
   * --file=~/somewhere and --directory=~/somewhere
   * --file=~$USER and --directory=~$USER

diff --git a/busdb b/busdb
--- a/busdb
+++ b/busdb
@@ -4,11 +4,11 @@
 #: Title           : busdb                                                                     #
 #: Sypnosis        : busdb [OPTIONS]... [ARGS]                                                 #
 #: Date Created    : Tue 30 Jan 2018 07:26:31 AM +08  /  Mon Jan 29 23:26:31 UTC 2018          #
-#: Last Edit       : Tue 18 Sep 2018 21:30:39 PM +08  /  Tue Sep 18 13:30:39 UTC 2018          #
+#: Last Edit       : Wed 19 Sep 2018 10:16:07 AM +08  /  Wed Sep 19 02:16:07 UTC 2018          #
 #: License         : GPL3+                                                                     #
-#: Version         : 1.0.0                                                                     #
+#: Version         : 1.0.1                                                                     #
 #: Author          : Jason V. Ferrer '<jetchisel@opensuse.org>'                                #
-#: Description     : A script to backup the sdb database.                                      #
+#: Description     : A backup script for sqlite3 database.                                     #
 #: Options         : [hfd]                                                                     #
 #: Home Page       : https://github.com/Jetchisel/sdb                                          #
 #: ExtComm         : file,mkdir,sqlite3                                                        #
@@ -100,6 +100,10 @@ ShowHelp() {
   echo "
 Usage: $script_name [OPTION]... [ARGUMENT]
 
+Back up sqlite3 database.
+
+A backup shell script for sqlite3 database.
+
 Options:
   -h, --help      Show this help.
   -f, --file      The sqlite3 database/file to backup.
@@ -111,16 +115,6 @@ Example:
   -f /path/to/the/database/mydatabase -d /path/to/the/directory/whereto/backup/
   --file /path/to/the/database/mydatabase --directory /path/to/the/directory/whereto/backup/
   --file=/path/to/the/database/mydatabase --directory=/path/to/the/directory/whereto/backup/
-
-AUTOMATED BACKUP:
-  Using cron:
-
-  0 * * * * \"\$HOME/bin/bsdb\" -f \"\$HOME/.bash_history.sqlite\" -d /Data
-
-  The script is in \"\$HOME/bin\"
-  The database is \"\$HOME/.bash_history.sqlite\"
-  The destination/directory is /Data
-  This runs every hour on openSUSE, consult the documentation of your cron see ''man 5 crontab''
 "
 }
 
@@ -146,32 +140,32 @@ time=$(printf '%(%H-%M-%S)T%s' -1)
 # Getops from scratch by D.J. Mills, https://github.com/e36freak/templates/blob/master/options #
 # ******************************************************************************************** #
 
-  optstring=BCDhf:d:
+optstring=hf:d:
 
-  unset options
+unset options
 
-  while (($#)); do
-    case $1 in
-      -[!-]?*)
-        for ((i=1; i<${#1}; i++)); do
-          c=${1:i:1}
-          options+=("-$c")
-          if [[ $optstring = *"$c:"* && ${1:i+1} ]]; then
-            options+=("${1:i+1}")
-            break
-          fi
-        done
-        ;;
-      --?*=*) options+=("${1%%=*}" "${1#*=}");;
-      --) options+=(--endopts);;
-      *) options+=("$1");;
-    esac
-    shift
-  done
+while (($#)); do
+  case $1 in
+    -[!-]?*)
+      for ((i=1; i<${#1}; i++)); do
+        c=${1:i:1}
+        options+=("-$c")
+        if [[ $optstring = *"$c:"* && ${1:i+1} ]]; then
+          options+=("${1:i+1}")
+          break
+        fi
+      done
+      ;;
+    --?*=*) options+=("${1%%=*}" "${1#*=}");;
+    --) options+=(--endopts);;
+    *) options+=("$1");;
+  esac
+  shift
+done
 
-  set -- "${options[@]}"
+set -- "${options[@]}"
 
-  unset options
+unset options
 
 # ******************************************************************************************** #
 #   If first option is not empty and it does not start with a dash then exit with an error.    #
@@ -185,45 +179,45 @@ time=$(printf '%(%H-%M-%S)T%s' -1)
 #                          Parse the command line arguments/options.                           #
 # ******************************************************************************************** #
 
-  while [[ $1 = -?* ]]; do
-    case $1 in
-      --help|-\?|-h)
-        ShowHelp
-        exit 0
-        ;;
-      --file|-f)
-        shift
-        [[ -n $1 ]] || die "Which database?" "try '$script_name --help'" 1
-        database=$1
-        [[ $database = '~/'* ]] && database=$HOME${database#*?}
-        if [[ $database = "~$__sdb_logname_"* ]]; then
-          (( EUID > 0 )) && database=${HOME%"$__sdb_logname_"}${database#*?}
-          (( EUID == 0 )) && database=/${database#*?}
-        fi
-        output=$(file -- "$database")
-        [[ "$output" = *'SQLite 3.x database'* ]] || die "Something seems to be wrong with [$database]" "file_type: [$output]" 1
-        file=1
-        ;;
-      --directory|-d)
-        shift
-        [[ -n $1 ]] || die "Which directory?" "backup destination not given!" 1
-        destination=$1
-        [[ $destination = '~/'* ]] && destination=$HOME${destination#*?}
-        if [[ $destination = "~$__sdb_logname_"* ]]; then
-          (( EUID > 0 )) && destination=${HOME%"$__sdb_logname_"}${destination#*?}
-          (( EUID == 0 )) && destination=/${destination#*?}
-        fi
-        [[ -d $destination ]] || die "$destination is not a directory!" "please fix the error, then try again." 1
-        [[ -x $destination ]] || die "Check your permissions in \`$destination'." "please fix the error, then try again." 1
-        [[ -w $destination ]] || die "Check your permissions in \`$destination'." "please fix the error, then try again." 1
-        [[ $destination = */ ]] && destination=${destination%/*}
-        directory=1
-        ;;
-        *)
-      die "invalid option -- '$1'" "try '$script_name --help'" 1
-    esac
-    shift
-  done
+while [[ $1 = -?* ]]; do
+  case $1 in
+    --help|-\?|-h)
+      ShowHelp
+      exit 0
+      ;;
+    --file|-f)
+      shift
+      [[ -n $1 ]] || die "Which database?" "try '$script_name --help'" 1
+      database=$1
+      [[ $database = '~/'* ]] && database=$HOME${database#*?}
+      if [[ $database = "~$LOGNAME"* ]]; then
+        (( EUID > 0 )) && database=${HOME%"$LOGNAME"}${database#*?}
+        (( EUID == 0 )) && database=/${database#*?}
+      fi
+      output=$(file -- "$database")
+      [[ "$output" = *'SQLite 3.x database'* ]] || die "Something seems to be wrong with [$database]" "file_type: [$output]" 1
+      file=1
+      ;;
+    --directory|-d)
+      shift
+      [[ -n $1 ]] || die "Which directory?" "backup destination not given!" 1
+      destination=$1
+      [[ $destination = '~/'* ]] && destination=$HOME${destination#*?}
+      if [[ $destination = "~$LOGNAME"* ]]; then
+        (( EUID > 0 )) && destination=${HOME%"$LOGNAME"}${destination#*?}
+        (( EUID == 0 )) && destination=/${destination#*?}
+      fi
+      [[ -d $destination ]] || die "$destination is not a directory!" "please fix the error, then try again." 1
+      [[ -x $destination ]] || die "Check your permissions in \`$destination'." "please fix the error, then try again." 1
+      [[ -w $destination ]] || die "Check your permissions in \`$destination'." "please fix the error, then try again." 1
+      [[ $destination = */ ]] && destination=${destination%/*}
+      directory=1
+      ;;
+      *)
+    die "invalid option -- '$1'" "try '$script_name --help'" 1
+  esac
+  shift
+done
 
 # ******************************************************************************************** #
 #      Make the -f and -d option non-optional, so exit if those are not given/specified.       #
